title: Debbie.codes
description: LeetCode 刷題筆記 & Python 學習記錄
theme: jekyll-theme-time-machine

author: Debbie Li
show_excerpts: true
paginate: 5


plugins:
  - jekyll-theme-time-machine


sass:
  style: compressed
