title: Debbie.codes
description: LeetCode 刷題筆記 & Python 學習記錄
theme: jekyll-theme-cayman

author: Debbie Li
show_excerpts: true
paginate: 5


plugins:
  - jekyll-theme-cayman


sass:
  style: compressed

include:
  - assets/css/custom.css
